# Generated by Django 5.0.7 on 2024-07-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeuai', models.CharField(max_length=10)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('lycee', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=255)),
                ('ppi', models.CharField(max_length=255)),
                ('annee_d_individualisation', models.FloatField(blank=True, null=True)),
                ('titreoperation', models.CharField(max_length=255)),
                ('enveloppe_prev_en_meur', models.FloatField(blank=True, null=True)),
                ('montant_des_ap_votes_en_meur', models.FloatField(blank=True, null=True)),
                ('mandataire', models.CharField(blank=True, max_length=255, null=True)),
                ('maitrise_d_oeuvre', models.CharField(blank=True, max_length=255, null=True)),
                ('notification_du_marche', models.DateField(blank=True, null=True)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_de_devolution', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_de_lots', models.FloatField(blank=True, null=True)),
                ('cao_attribution', models.DateField(blank=True, null=True)),
                ('etat_d_avancement', models.CharField(max_length=255)),
                ('annee_de_livraison', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
