FROM node:alpine

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app

COPY . /app

# Install any needed packages specified in package.json
RUN npm install

