services:
  api:
    build: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - backend/.env
      - backend/.env.override
    restart: always
  frontend:
    build: frontend
    command: npm start -- --host 0.0.0.0
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
    depends_on:
      - api
    restart: always
  db:
    image: postgres:15
    platform: linux/x86_64
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=investment_portfolio
      - POSTGRES_PASSWORD=investment_portfolio
      - POSTGRES_DB=investment_portfolio
    restart: on-failure
